### ISSUE TITLE
Provider can not be found

### ISSUE THREAD

**Issue by adityadrs** [issus/CelestialADB-Desktop#11]
I downloaded the Altium library from your other repository (https://github.com/issus/altium-library) and followed the steps stated in this repository. But for some reason I am getting the error "Provider can not be found". 
Attached is the screenshot of the same error. (I am getting this error in every library)

![capture](https://user-images.githubusercontent.com/26600387/33519481-4f1d46a6-d79f-11e7-8d84-6e784e1e7716.PNG)

**Comment by issus** [comment]
See database's wiki: https://github.com/issus/altium-library/wiki#error-messages
