### ISSUE TITLE
Altium 18 issue...

### ISSUE THREAD

**Issue by nweaver** [issus/CelestialADB-Desktop#13]
I checked out the altium-library archive, set up an Azure account and Celestial ADB, clicked on "update UDL settings".  

But when I try to use the library (by adding it to my search path), I get a "An error occured while establishing a connection to the database.  ALtium Designer requires that the 64-bit Microsoft Access Database Engine be installed".  But this system (Win10) has a fresh install of Office, which should be the 64b version by default these days.

Suggestions?

Oh, and thanks for doing this!

**Comment by nweaver** [comment]
Found out problem:  OFfice defaults to 32b install and 64b is a semi-hidden option!

**Comment by nweaver** [comment]
Crud, did a manual install of Office 64b, did a manual install of the this component: https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=13255, neither seemed to work.  Thoughts?

**Comment by issus** [comment]
Can you try to install the Microsoft SQL Server 2012 Native Client? It can be found on this page (scroll all the way down to MICROSOFT SQL SERVER CONNECTIVITY FEATURE PACK COMPONENTS or search the page for sqlncli.msi).

**Comment by nweaver** [comment]
Worked, thanks!

**Comment by nvonbulow** [comment]
@issus I just had the same issue, and it also worked for me. It might be a good idea to put the solution in the readme to save several people the trouble of searching for this issue.

**Comment by issus** [comment]
Its in the wiki...

**Comment by phatpaul** [comment]
Hmm, I got here too after getting the error message and didn't see it in the Wiki.

I would contribute my error message to the Wiki, but unfortunately I didn't save the screenshot before I fixed it.
