### ISSUE TITLE
Resolation problem

### ISSUE THREAD

**Issue by yldzmuhammed** [issus/CelestialADB-Desktop#14]
Hi,
I am trying to create an account. But since i cant use the program correctly i cant crate an account.The problem is my laptops screen res. 1366x768.
I can not see create account button. How can fix this?
![celestial](https://user-images.githubusercontent.com/2121759/34328691-fde2e9b2-e8f6-11e7-9dbe-69dd5580bd2a.jpg)

**Comment by issus** [comment]
There's a fix checked in for this - just waiting for code signing
certificate to be issued before compiling and publishing.

You can build from source if you want a fix right away.

**Comment by yldzmuhammed** [comment]
Some how i get over it but now i have a new problem.After that screen (above) i should enter the activation code (below). But i dont have it. How can i solve this?What should i do?
![celestial2](https://user-images.githubusercontent.com/2121759/34342519-9da09108-e9c3-11e7-8e81-0e887caafff3.jpg)
