### ISSUE TITLE
Problem installing the library when setting up the connection

### ISSUE THREAD

**Issue by Luisdlahuerta** [issus/CelestialADB-Desktop#15]
Hello Friend,

First, thank you for this work, it's very good.
I have a problem installing the library when configuring the connection, I open the udl file created with double click and execute the notepad. I'm standing in that step.
From there it does not allow me to add the library to altium, it sends me the following error:
"Microsoft OLE DB Service Components: Class not registered"
![captura1](https://user-images.githubusercontent.com/35171936/34641173-4c715ba0-f300-11e7-869d-0c7245c5d275.PNG)
![captura2](https://user-images.githubusercontent.com/35171936/34641203-bfe20abc-f300-11e7-8e37-690ba728b135.PNG)

My user in azure is:  LuisJE

I hope you can help.
Thank you very much in advance.

**Comment by issus** [comment]
Install the Microsoft SQL Server 2012 Native Client. It can be found here:
https://www.microsoft.com/en-us/download/details.aspx?id=29065 (scroll all
the way down to MICROSOFT SQL SERVER CONNECTIVITY FEATURE PACK COMPONENTS
or search the page for sqlncli.msi).

**Comment by Luisdlahuerta** [comment]
Thank you very much for your quick response.
God bless you.
I'm going to get on with it.
thanks, again
