### ISSUE TITLE
ERROR: Email address/user does not exist

### ISSUE THREAD

**Issue by bgsuello** [issus/CelestialADB-Desktop#16]
![image](https://user-images.githubusercontent.com/11388006/35956670-2d9db9a8-0cd2-11e8-9eee-26bb4ec0bd69.png)

**Comment by issus** [comment]
Make sure you have registered before you try to resend the activation email.

**Comment by bgsuello** [comment]
I did but I didn't receive any email regarding my activation.

**Comment by bgsuello** [comment]
@issus , **it is fixed now**, I don't know what happen, but when I try it again this morning It successfully registered and sent me an activation code.


Thanks,
