### ISSUE TITLE
Code Signing Cert

### ISSUE THREAD

**Issue by GeorgeHahn** [issus/CelestialADB-Desktop#2]
A number of years ago, I reached out to [Digicert](https://twitter.com/DigiCert) on Twitter (specifically, [Flavio Martins](https://twitter.com/flavmartins)) and was given a free code signing cert for my FOSS project. I don't know if they still do this, but it may be worth asking!

**Comment by issus** [comment]
There used to be a couple of places that offered free/very cheap code signing certificates (based on blogs and StackExchange comments), but they appear to have all dried up during 2016. I wonder if their CA cert was dropping in reputation with Microsoft because of it?
