### ISSUE TITLE
An error occured attempting to install Celestial ADB Desktop

### ISSUE THREAD

**Issue by yldzmuhammed** [issus/CelestialADB-Desktop#24]
When i try to install Celestial ADB Desktop it says me that

> An error occurred trying to download 'https://altiumservices.azurewebsites.net/Desktop/CelestialADBDesktop.application'.
> 
> See the setup log file located at 'C:\Users\muham\AppData\Local\Temp\VSD272D.tmp\install.log' for more information.

When i try to run it says me that "Select Sertificate":

![altium-issus](https://user-images.githubusercontent.com/2121759/44550623-75694400-a72d-11e8-9bef-24ee55fdb361.PNG)

I cant use altium library on my pc (altium).

What should i do?

**Comment by ydessert** [comment]
same problem here.

When I try to access 'https://altiumservices.azurewebsites.net/Desktop/CelestialADBDesktop.application'.
I got the error: Error 403 - This web app is stopped

**Comment by yldzmuhammed** [comment]
Fixed by itself. Thanks.
