### ISSUE TITLE
No activation email

### ISSUE THREAD

**Issue by lucasgerads** [issus/CelestialADB-Desktop#26]
I tried to register, but I haven't received an activation email (checked my spam folder etc.). Tried to resend a couple of times. My username is the same as my github name (lucasgerads).

**Comment by ThomasW69** [comment]
me too

**Comment by issus** [comment]
Its not, I just don't have much internet access at the moment. It's a known issue right now, and it's not one I'm going to fix at the moment as we're working on getting a dedicated server for the database to put the firewall issues to rest, and that will fix the activation email too.
