### ISSUE TITLE
Error occurred while establishing a connection to the database

### ISSUE THREAD

**Issue by rdmeneze** [issus/CelestialADB-Desktop#27]
Hi!
I'm using the AD19 in a Windows 7 64 bits machine. 
I have already installed the 64-bit Microsoft Access Database Engine. 

Follows the error that altium issues:  
![image](https://user-images.githubusercontent.com/4107933/52410551-eb454a00-2ad8-11e9-8d5a-915d2fc10a24.png)

**Comment by issus** [comment]
Install the Microsoft SQL Server 2012 Native Client. It can be found on this (https://www.microsoft.com/en-us/download/details.aspx?id=29065) page (scroll all the way down to MICROSOFT SQL SERVER CONNECTIVITY FEATURE PACK COMPONENTS or search the page for sqlncli.msi).
