### ISSUE TITLE
Error in connection with the database

### ISSUE THREAD

**Issue by rdmeneze** [issus/CelestialADB-Desktop#28]
Now I tried in my house. I'm using a AD17 in a Windows 7 64 bit machine.

![image](https://user-images.githubusercontent.com/4107933/52465554-4c275d80-2b7f-11e9-8d58-825eb86ad617.png)

**Comment by dommyet** [comment]
Did you try opening the udl file directly? If you got something like "provider not found" then here is the solution.

Open the udl file with a text editor you will see the provider is SQLNCLI11.1 which you need "Microsoft® SQL Server® 2012 Native Client - QFE" installed.

And it can be downloaded for free https://www.microsoft.com/en-us/download/details.aspx?id=50402

**Comment by issus** [comment]
You don't have a firewall rule set - make sure the desktop tool is showing you have a firewall rule set in the top right, and that the IP address matches what the error has. If the IP address doesn't match, make sure you don't have a web proxy configured in windows/internet explorer/edge, and that you don't have a VPN connection open. If the IP address still doesn't match, well, your ISP is doing something funky which makes it so your actual IP isn't used for web browsing.

If you don't have any luck, hopefully we're just a few weeks from a dedicated server which will make the firewall rule business defunct.
