### ISSUE TITLE
Activation Fails

### ISSUE THREAD

**Issue by GeorgeHahn** [issus/CelestialADB-Desktop#3]
Hi,

I am currently unable to activate a new account - the activation fails with the message 'An error has occurred'.

I assume this is an issue on the server side, but I'm happy to debug it if you think it's on the application side.

Best,
George

**Comment by issus** [comment]
Hmm, I suspect it might have something to do with the fact I can't find an user for you?! Did you use the email address listed on your GitHub profile?

Can you please forward me your registration email (markh@rris.com.au).

If you managed to get through to the point it sent you the email but somehow managed to not get an account create for yourself, that is certainly interesting and will need to be figured out!

**Comment by dadede** [comment]
Hello,
I think I have a similar problem. It crashes when I try to enter the activation code.
Please let me know what you need to try figuring the cause of the error.
Thanks!

**Comment by issus** [comment]
Can you please forward me the registration email with the activation code? Looks like you got an account setup, but it has not activated.

**Comment by dadede** [comment]
dnld.adede@gmail.com

WekfWVI7y8/fqxSWbWtvfTkVlqY0ugdMa6a0COkpKB6eR1Q3gMNzGQAhhpzbnsrKUtOrxgY
yWrSaiBao527l32DS8NUqvAJAtQkaurvbFR2caDmZsbfWl1VuT9Xi5A4wMx2
2NuOSEQaGtA6qJQBDODHX/HZpQIdoWgaAuSqulWxyCqVsCFxj3P8NsSe2y01z

**Comment by GeorgeHahn** [comment]
Good call on mine - I'm pretty sure I only clicked the activate button and never clicked the signup button.

Apologies for that!

Sent from Outlook for Android

________________________________

**Comment by issus** [comment]
@dadede can you try again, I've added a bunch more error checking and return error messages back a bit more verbosely, plus I'm emailing myself the full exception for any activation issue (hopefully! wasn't able to test that).

You'll likely get exactly the same error, but in doing so will give me some idea of where it's going wrong!

- Mark

**Comment by issus** [comment]
@GeorgeHahn Looks like you have a user account now and were able to activate successfully?

**Comment by dadede** [comment]
Debug detail from V2015

System.InvalidOperationException was unhandled
Message: An unhandled exception of type 'System.InvalidOperationException'
occurred in WindowsBase.dll
Additional information: '{DependencyProperty.UnsetValue}' is not a valid
value for property 'Fill'.

Let me know how I can be of assistance.

**Comment by reinaldoaf** [comment]
I get the same problem,
when I register, no get email on reinaldo@desenvolvedores.net, and when I try resend show error "An error has occurred."

**Comment by logictom** [comment]
I posted a comment on the issue in the db repo but looks like this is where I should have posted.
Having the same issue, "An error has occurred."

**Comment by spatel10x** [comment]
I got same error too.

**Comment by A-GammaL** [comment]
Got the same error too. Signed up with the same e-mail here.

**Comment by issus** [comment]
I'm still unable to replicate this... if you have this issue please send me a message with your email address and the username you used for the altiumdb to markh@rris.com.au - I can't see other github users emails!

**Comment by issus** [comment]
As a note, less than 5% of registered accounts haven't been activated, so this could be a tough one to track down - any input would be much appreciated.

**Comment by devttys1** [comment]
I get the same message "An error has occurred." 

I tried debugging it from VS, and the response from the server is;
```
response.StatusCode = InternalServerError
response.ErrorException = null 
response.ErrorMessage = null
```

**Comment by issus** [comment]
I pushed new web services up last night, so I think perhaps I might have broken something - I'm looking into it now ;)

**Comment by issus** [comment]
Fixed - I add a couple of fields to the database to save me a few hours a month on maintenance and forgot to initialise it for new users.

I'm guessing the original Activation Fails issue still present, and I still can't replicate it. Anybody who has the issue should still post about it, and if possible forward me any emails you got when signing up :)

**Comment by devttys1** [comment]
Thanks, that resolved the issue for me; I was able to create and activate an account.

**Comment by yanw4tanabe** [comment]
Got the same error here ("An error occured" - while trying to get the verification code). I also signed up with the same e-mail at github.

**Comment by issus** [comment]
Yan's issue was a missing user account and is now resolved.

**Comment by enerik** [comment]
Hello 
I am having the same issue , after that i tried to log in . 
It was succesful but when i open the udl to enter my credential it said that my credentials are not correct .
I am sure about it since i can log in with them to Celestial DB desktop .
Help needed.
Regards

**Comment by yldzmuhammed** [comment]
Hi there. I cant get an account. I insallted this program.But i can not create an account.I still did not get any e-mail about account cration.
What should i do?

**Comment by ThomasW69** [comment]
Hi,
I didn't received an activation email. Tried it several times.
Email: thomas.westerhoff@iosb-ast.fraunhofer.de
Regards
