### ISSUE TITLE
Password complexity hint

### ISSUE THREAD

**Issue by rcairman** [issus/CelestialADB-Desktop#4]
Hi,

The app only informs user that the password is not complex enough. It didn't give any instructions on how complicated it should be. While searching for this online, I also found a note that Azure accepts passwords from 8 to 16 characters which could mean that too complex is not good either.

**Comment by issus** [comment]
Azure's password complexity requirements are linked right from the main readme :) https://github.com/issus/CelestialADB-Desktop
