### ISSUE TITLE
UDL file location - wrong displayed name

### ISSUE THREAD

**Issue by rcairman** [issus/CelestialADB-Desktop#5]
Hi,

unless I misunderstand this message, there is an error in drive letter:

![image](https://cloud.githubusercontent.com/assets/11981960/26310525/54339186-3f01-11e7-8c65-1662b254f830.png)

Apart from naming, the .udl file was created on D: as I wanted

**Comment by issus** [comment]
Do you browse to an existing dblib, or the dblib from git? If so, it's reading the udl file location from the Database library file.

The program will always create the new UDL file with the same path/name as the dblib, just with the extension changed.

**Comment by rcairman** [comment]
It was a fresh install from git. Your explanation is clear, it is just that unexperienced user may think it will create the file on C:

**Comment by issus** [comment]
Thats a fair point, what if it was change to "Current Universal Data Link (.udl) location: ..."?
