### ISSUE TITLE
Unable to access library in altium

### ISSUE THREAD

**Issue by shewshew79** [issus/CelestialADB-Desktop#7]
Hi,

I have been using the library for a while now with no problem, My IP is dynamic so I have always clicked the Azure link at the top and access has been granted when the library doesn't load in Altium. This however has made me become lazy and I have forgotten my user name and password. Basically my computer has forgotten the login and so have I. My question is how do I reset my access? There is no option available to do that. I run the desktop software and it wants a login.

Regards

M

**Comment by issus** [comment]
If you open the .udl file in your library directory, the username and password is in there in plain text :)
