### ISSUE TITLE
Issue with IP changing

### ISSUE THREAD

**Issue by newantman** [issus/CelestialADB-Desktop#8]
Hi,

The software's been working great until last week when my power went out and the router rebooted which gave me a new IP. I've clicked the Azure access firewall and it is green but I still get the data link error. Any help is appreciated!

![image](https://user-images.githubusercontent.com/33417526/32436268-75dee866-c31e-11e7-941f-1b7d6d158e8e.png)
![image](https://user-images.githubusercontent.com/33417526/32436382-e16900e4-c31e-11e7-8057-3067de8b60ca.png)

**Comment by issus** [comment]
I see two firewall rules for you for two accounts, but for different ip addresses. Perhaps try restarting your computer and then try the app again?

**Comment by newantman** [comment]
Hi Mark,

Thanks for your reply, it was very helpful. So I think this issue was caused by a socks5 proxy that I was using, it seems the celestial library is communicating with the Azure database through the proxy while it was showing an error for my local IP. The connection works after I've disabled the proxy.

Thank you so much for your prompt response!

**Comment by issus** [comment]
Yep, well the only way it has to figure out your IP address is to look at the host which made the webapi call, if you're using a proxy - then that's the proxy.
